# Example Configuration File for DCAM
general:
  year: 2022
  month: 12
  day: 22
  verbose: 1
  numMonteCarloRuns: 1 # 1 specifies no monte carlo analysis
  save: 1
  outputDir: # If user wants to output result files to an external drive, otherwise save to current output directory
aircraft:
  time: 100 # [s]
  frequency: 200 # [Hz]
  waypoints: constantTurn
  lookaheadDistance: 50 # [m]
  initialState:
    latitude: 32.612788581736706 # [degrees]
    longitude: -85.43535088858731 # [degrees]
    u: 75 # [m/s]
    v: 0 # [m/s]
    w: 0 # [m/s]
    p: 0 # [rad/s]
    q: 0 # [rad/s]
    r: 0 # [rad/s]
    x: 0 # [m]
    y: 0 # [m]
    z: -1000 # [m]
    phi: 0 # [rad]
    theta: 4*pi/180 # [rad]
    psi: pi # [rad]
noise:
  FVDM:
    wind:
      direction: 360 # (1) [deg]
      directionTS: 60 # (1) [s]
      velocity: 30 # (1) [m/s]
      velocityTS: 15 # (1) [s]
    gravity:
      force: [1;1;1] # (3,1) [N]
      forceTS: 0.1 # (1) [s]
      moment: [3;3;3] # (3,1) [N*m]
      momentTS: 0.3 # (1) [s]
    aero:
      force: [250;125;125] # (3,1) [N]
      forceTS: 0.5 # (1) [s]
      moment: [1000;500;500] # (3,1) [N*m]
      momentTS: 1.5 # (1) [s]
    engine:
      force: [100;25;25] # (3,1) [N]
      forceTS: 5 # (1) [s]
      moment: [500;125;125] # (3,1) [N*m]
      momentTS: 10 # (1) [s]
  IMU1:
    accelerometer:
      resolution: 0 # (1) [(m/s2)/LSB]
      constantOffsetBias: [0 0 0] # (1,3) [m/s2]
      axesSkew: [100 0 0;0 100 0;0 0 100] # (3,3) [%]
      velocityRandomWalk: # (1,3) [(m/s2)/sqrt(Hz)]
      biasInstability: # (1,3) [m/s2]
      accelerationRandomWalk: # (1,3) [(m/s2)*sqrt(Hz)]
      temperatureBias: # (1,3) [(m/s2)/C]
      temperatureScaleFactor: # (1,3) [%/C]
    gyroscope:
      resolution: 0 # (1) [(rad/s)/LSB]
      constantOffsetBias: [0 0 0] # (1,3) [rad/s]
      axesSkew: [100 0 0;0 100 0;0 0 100] # (3,3) [%]
      accelerationBias: # (1,3) [(rad/s)/(m/s2)]
      angleRandomWalk: # (1,3) [(rad/s)/sqrt(Hz)]
      biasInstability: # (1,3) [rad/s]
      gyroscopeRandomWalk: # (1,3) [(rad/s)*sqrt(Hz)]
      temperatureBias: # (1,3) [(rad/s)/C]
      temperatureScaleFactor: # (1,3) [%/C]
  IMU2:
    accelerometer:
      resolution: 0 # (1) [(m/s2)/LSB]
      constantOffsetBias: [0 0 0] # (1,3) [m/s2]
      axesSkew: [100 0 0;0 100 0;0 0 100] # (3,3) [%]
      velocityRandomWalk: # (1,3) [(m/s2)/sqrt(Hz)]
      biasInstability: # (1,3) [m/s2]
      accelerationRandomWalk: # (1,3) [(m/s2)*sqrt(Hz)]
      temperatureBias: # (1,3) [(m/s2)/C]
      temperatureScaleFactor: # (1,3) [%/C]
    gyroscope:
      resolution: 0 # (1) [(rad/s)/LSB]
      constantOffsetBias: [0 0 0] # (1,3) [rad/s]
      axesSkew: [100 0 0;0 100 0;0 0 100] # (3,3) [%]
      accelerationBias: # (1,3) [(rad/s)/(m/s2)]
      angleRandomWalk: # (1,3) [(rad/s)/sqrt(Hz)]
      biasInstability: # (1,3) [rad/s]
      gyroscopeRandomWalk: # (1,3) [(rad/s)*sqrt(Hz)]
      temperatureBias: # (1,3) [(rad/s)/C]
      temperatureScaleFactor: # (1,3) [%/C]
  IMU3:
    accelerometer:
      resolution: 0 # (1) [(m/s2)/LSB]
      constantOffsetBias: [0 0 0] # (1,3) [m/s2]
      axesSkew: [100 0 0;0 100 0;0 0 100] # (3,3) [%]
      velocityRandomWalk: # (1,3) [(m/s2)/sqrt(Hz)]
      biasInstability: # (1,3) [m/s2]
      accelerationRandomWalk: # (1,3) [(m/s2)*sqrt(Hz)]
      temperatureBias: # (1,3) [(m/s2)/C]
      temperatureScaleFactor: # (1,3) [%/C]
    gyroscope:
      resolution: 0 # (1) [(rad/s)/LSB]
      constantOffsetBias: [0 0 0] # (1,3) [rad/s]
      axesSkew: [100 0 0;0 100 0;0 0 100] # (3,3) [%]
      accelerationBias: # (1,3) [(rad/s)/(m/s2)]
      angleRandomWalk: # (1,3) [(rad/s)/sqrt(Hz)]
      biasInstability: # (1,3) [rad/s]
      gyroscopeRandomWalk: # (1,3) [(rad/s)*sqrt(Hz)]
      temperatureBias: # (1,3) [(rad/s)/C]
      temperatureScaleFactor: # (1,3) [%/C]
