# Example Configuration File for DCAM
general:
  year: 2022
  month: 12
  day: 22
  verbose: 1
  numMonteCarloRuns: 1 # 1 specifies no monte carlo analysis
  save: 1
  outputDir: # If user wants to output result files to an external drive, otherwise save to current output directory
aircraft:
  time: 1000 # [s]
  frequency: 50 # [Hz]
  waypoints: longtrajectory
  lookaheadDistance: 50 # [m]
  initialState:
    u: 70 # [m/s]
    v: 0 # [m/s]
    w: 0 # [m/s]
    p: 0 # [rad/s]
    q: 0 # [rad/s]
    r: 0 # [rad/s]
    x: 0 # [m]
    y: 0 # [m]
    z: -1000 # [m]
    phi: 0 # [rad]
    theta: 4*pi/180 # [rad]
    psi: pi # [rad]
noise:
  IMUFrequency: 10 # [Hz]
  FVDM:
    wind:
      direction: 360 # (1) [deg]
      directionTS: 60 # (1) [s]
      velocity: 30 # (1) [m/s]
      velocityTS: 15 # (1) [s]
    gravity:
      force: [1;1;1] # (3,1) [N]
      forceTS: 10 # (1) [s]
      moment: [3;3;3] # (3,1) [N*m]
      momentTS: 10 # (1) [s]
    aero:
      force: [250;125;125] # (3,1) [N]
      forceTS: 10 # (1) [s]
      moment: [1000;500;500] # (3,1) [N*m]
      momentTS: 10 # (1) [s]
    engine:
      force: [100;25;25] # (3,1) [N]
      forceTS: 10 # (1) [s]
      moment: [500;125;125] # (3,1) [N*m]
      momentTS: 10 # (1) [s]
  IMU1:
    accelerometer:
      resolution: 0 # (1) [(m/s2)/LSB]
      constantOffsetBias: [0 0 0] # (1,3) [m/s2]
      axesSkew: [100 0 0;0 100 0;0 0 100] # (3,3) [%]
      velocityRandomWalk: [0.08 0.08 0.08] # (1,3) [(m/s2)/sqrt(Hz)]
      biasInstability: [0.05 0.05 0.05] # (1,3) [m/s2]
      accelerationRandomWalk: [0.005 0.005 0.005] # (1,3) [(m/s2)*sqrt(Hz)]
      temperatureBias: [0.0087266 0.0087266 0.0087266] # (1,3) [(m/s2)/C]
      temperatureScaleFactor: [0.1 0.1 0.1] # (1,3) [%/C]
    gyroscope:
      resolution: 0 # (1) [(rad/s)/LSB]
      constantOffsetBias: [0 0 0] # (1,3) [rad/s]
      axesSkew: [100 0 0;0 100 0;0 0 100] # (3,3) [%]
      accelerationBias: [0.005 0.005 0.005] # (1,3) [(rad/s)/(m/s2)]
      angleRandomWalk: [0.0005 0.0005 0.0005] # (1,3) [(rad/s)/sqrt(Hz)]
      biasInstability: [0.0007 0.0007 0.0007] # (1,3) [rad/s]
      gyroscopeRandomWalk: [0.00060187 0.00060187 0.00060187] # (1,3) [(rad/s)*sqrt(Hz)]
      temperatureBias: [0.0087266 0.0087266 0.0087266] # (1,3) [(rad/s)/C]
      temperatureScaleFactor: [0.1 0.1 0.1] # (1,3) [%/C]
  IMU2:
    accelerometer:
      resolution: 0 # (1) [(m/s2)/LSB]
      constantOffsetBias: [0 0 0] # (1,3) [m/s2]
      axesSkew: [100 0 0;0 100 0;0 0 100] # (3,3) [%]
      velocityRandomWalk: [0.03 0.03 0.03] # (1,3) [(m/s2)/sqrt(Hz)]
      biasInstability: [0.01 0.01 0.01] # (1,3) [m/s2]
      accelerationRandomWalk: [0.001 0.001 0.001] # (1,3) [(m/s2)*sqrt(Hz)]
      temperatureBias: [0.087266 0.087266 0.087266] # (1,3) [(m/s2)/C]
      temperatureScaleFactor: [0.075 0.075 0.075] # (1,3) [%/C]
    gyroscope:
      resolution: 0 # (1) [(rad/s)/LSB]
      constantOffsetBias: [0 0 0] # (1,3) [rad/s]
      axesSkew: [100 0 0;0 100 0;0 0 100] # (3,3) [%]
      accelerationBias: [0.00005 0.00005 0.00005] # (1,3) [(rad/s)/(m/s2)]
      angleRandomWalk: [0.00005 0.00005 0.00005] # (1,3) [(rad/s)/sqrt(Hz)]
      biasInstability: [0.000005 0.000005 0.000005] # (1,3) [rad/s]
      gyroscopeRandomWalk: [0.000080187 0.000080187 0.000080187] # (1,3) [(rad/s)*sqrt(Hz)]
      temperatureBias: [0.01 0.01 0.01] # (1,3) [(rad/s)/C]
      temperatureScaleFactor: [0.075 0.075 0.075] # (1,3) [%/C]
  IMU3:
    accelerometer:
      resolution: 0 # (1) [(m/s2)/LSB]
      constantOffsetBias: [0 0 0] # (1,3) [m/s2]
      axesSkew: [100 0 0;0 100 0;0 0 100] # (3,3) [%]
      velocityRandomWalk: [0.0005 0.0005 0.0005] # (1,3) [(m/s2)/sqrt(Hz)]
      biasInstability: [0.0003 0.0003 0.0003] # (1,3) [m/s2]
      accelerationRandomWalk: [
          0.0000013729310000000002 0.0000013729310000000002 0.0000013729310000000002,
        ] # (1,3) [(m/s2)*sqrt(Hz)]
      temperatureBias: [0.0087266 0.0087266 0.0087266] # (1,3) [(m/s2)/C]
      temperatureScaleFactor: [0.04 0.04 0.04] # (1,3) [%/C]
    gyroscope:
      resolution: 0 # (1) [(rad/s)/LSB]
      constantOffsetBias: [0 0 0] # (1,3) [rad/s]
      axesSkew: [100 0 0;0 100 0;0 0 100] # (3,3) [%]
      accelerationBias: [0.00016667 0.00016667 0.00016667] # (1,3) [(rad/s)/(m/s2)]
      angleRandomWalk: [0.0000005 0.0000005 0.0000005] # (1,3) [(rad/s)/sqrt(Hz)]
      biasInstability: [0.00000005 0.00000005 0.00000005] # (1,3) [rad/s]
      gyroscopeRandomWalk: [0.000060187 0.000060187 0.000060187] # (1,3) [(rad/s)*sqrt(Hz)]
      temperatureBias: [0.0087266 0.0087266 0.0087266] # (1,3) [(rad/s)/C]
      temperatureScaleFactor: [0.05 0.05 0.05] # (1,3) [%/C]
